### ISSUE TITLE
개인, 이력서 관련 기능 API 연동

### ISSUE THREAD

**Issue by cshharry** [WooRibound/WooRibound-WEB#29]
## 🛠️ 작업 설명
>개인 회원 정보, 이력서 관련 기능 API 연동

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [ ] 개인 회원 정보 조회
- [ ] 개인 회원 정보 수정
- [ ] 이력서 조회
- [ ] 이력서 등록
- [ ] 이력서 수정
- [ ] 우바 점수 조회
- [ ] 알림 목록 조회
- [ ] 알림 내용 상세 조회

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
