### ISSUE TITLE
기업 회원 공고 관련 기능 API 연동

### ISSUE THREAD

**Issue by haewoni** [WooRibound/WooRibound-WEB#41]
## 🛠️ 작업 설명
> 기업 회원 관련 기능 API 연동

## 🔍 Todo
> 기업 회원 관련 기능# 🛠️ 작업 설명
> 기업 회원 관련 기능 API 연동

## 🔍 Todo
> 기업 회원 관련 기능

- [ ] 기업 공고 조회
- [ ] 기업 공고 상세 조회
- [ ]  기업 공고 등록
- [ ]  기업 공고 지원자 조회
- [ ]  기업 공고 지원자 이력서 조회
- [ ] 기업 공고 직무별 인재 추천

## 📃 참고한 출처
>
