### ISSUE TITLE
채용공고 불러오는 함수 중복

### ISSUE THREAD

**Issue by 2oo1s** [WooRibound/WooRibound-WEB#53]
## 🐛 버그 설명
>어떤 버그인지 간략하게 설명해주세요!

실행 시, 발생하는 오류 수정

## 🔍 Todo
> 수정할 사항항에 대해 적어주세요!

- [ ] individualUserService.js 내 중복되는 fetchJobPosting() 함수 제거 (adminService.js에도 작성된 함수)
- [ ] JobPostingDetail.vue에서 사용되지 않는 import문 제거
- [ ] JobPostingPage.vue에서 사용되는 함수 import문 추가

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
