### ISSUE TITLE
서비스 관리자 버그 해결

### ISSUE THREAD

**Issue by 2oo1s** [WooRibound/WooRibound-WEB#62]
## 🐛 버그 설명
>어떤 버그인지 간략하게 설명해주세요!

서비스 관리자 화면에서 예외 발생되는 상황일 시, NotFound 화면으로 이동하게 수정

## 🔍 Todo
> 수정할 사항항에 대해 적어주세요!

- [x] 존재하지 않는 사용자의 이력서를 조회하려고 하는 경우
- [x] 존재하지 않는 채용공고를 조회하려고 하는 경우
- [x] 존재하지 않는 지혜를 조회하려고 하는 경우
- [x] 주소 저장에 따른 지역 필터링 값 수정
- [ ] 화면 비율에 따른 css 적용 안되는 부분 수정

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
